<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Cartpage.aspx.cs" Inherits="Cartpage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p>
    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        Height="250px" Width="766px" DataSourceID="SqlDataSource1" ShowFooter="True" 
            onrowdeleting="GridView1_RowDeleting" 
            onselectedindexchanged="GridView1_SelectedIndexChanged" 
            AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#CCCCCC" 
            BorderStyle="None" BorderWidth="1px" CellPadding="3" 
            onrowdatabound="GridView1_RowDataBound" EnableTheming="False" 
              
            >
        <Columns>
            <asp:BoundField DataField="id" HeaderText="Product Id" >
            <ItemStyle HorizontalAlign="Center" Height="8px" Width="10px"  />
            </asp:BoundField>
            <asp:BoundField DataField="productname" HeaderText="Product Name">
            <ItemStyle HorizontalAlign="Center" Height="8px" Width="10px"/>
            </asp:BoundField>
            <asp:ImageField DataImageUrlField="productpic" HeaderText="Product Image">
                <ControlStyle Height="200px" Width="250px" />
                  <ItemStyle HorizontalAlign="Center" Height="8px" Width="10px" />
            </asp:ImageField>
            <asp:BoundField DataField="price" HeaderText="Price">
            <ItemStyle HorizontalAlign="Center" Height="8px" Width="10px" />
            </asp:BoundField>
            <asp:BoundField DataField="quantity" HeaderText="Quantity">
            <ItemStyle HorizontalAlign="Center" Height="8px" Width="10px" />
            </asp:BoundField>
            <asp:TemplateField HeaderText="Amount">
            <ItemTemplate>
                <asp:Label ID="Label1" runat="server" Text='<% # Convert.ToInt32(Eval("price")) * Convert.ToInt32(Eval("quantity")) %>'></asp:Label>
            </ItemTemplate>
            <FooterTemplate>
            Total Amount = 
            <asp:Label ID="lbltotal" runat="server" Text="lbl"></asp:Label>
            </FooterTemplate>
                <ItemStyle HorizontalAlign="Center" />
            </asp:TemplateField>
        </Columns>
        
        <EditRowStyle Height="150px" Width="150px" />
        
        <FooterStyle BackColor="#006699" ForeColor="White" />
        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#007DBB" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#00547E" />
        
    </asp:GridView>
</p>
    <p>
        <asp:Button ID="Button2" runat="server"  
            style="font-weight: 700; color: #FFFFFF; background-color: #009900" 
            Text="Place Order" onclick="Button2_Click" />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:jacob %>" 
            
            SelectCommand="SELECT * FROM [carttable]" 
            DeleteCommand="DELETE FROM [carttable] WHERE [id] = @original_id"
            ConflictDetection="CompareAllValues" 
            InsertCommand="INSERT INTO [carttable] ([id], [username], [productname], [productpic], [price], [quantity]) VALUES (@id, @username, @productname, @productpic, @price, @quantity)" 
            OldValuesParameterFormatString="original_{0}" 
            UpdateCommand="UPDATE [carttable] SET [username] = @username, [productname] = @productname, [productpic] = @productpic, [price] = @price, [quantity] = @quantity WHERE [id] = @original_id AND (([username] = @original_username) OR ([username] IS NULL AND @original_username IS NULL)) AND (([productname] = @original_productname) OR ([productname] IS NULL AND @original_productname IS NULL)) AND (([productpic] = @original_productpic) OR ([productpic] IS NULL AND @original_productpic IS NULL)) AND (([price] = @original_price) OR ([price] IS NULL AND @original_price IS NULL)) AND (([quantity] = @original_quantity) OR ([quantity] IS NULL AND @original_quantity IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_id" Type="Int32" />
                <asp:Parameter Name="original_username" Type="String" />
                <asp:Parameter Name="original_productname" Type="String" />
                <asp:Parameter Name="original_productpic" Type="String" />
                <asp:Parameter Name="original_price" Type="Int64" />
                <asp:Parameter Name="original_quantity" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="id" Type="Int32" />
                <asp:Parameter Name="username" Type="String" />
                <asp:Parameter Name="productname" Type="String" />
                <asp:Parameter Name="productpic" Type="String" />
                <asp:Parameter Name="price" Type="Int64" />
                <asp:Parameter Name="quantity" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="username" Type="String" />
                <asp:Parameter Name="productname" Type="String" />
                <asp:Parameter Name="productpic" Type="String" />
                <asp:Parameter Name="price" Type="Int64" />
                <asp:Parameter Name="quantity" Type="Int32" />
                <asp:Parameter Name="original_id" Type="Int32" />
                <asp:Parameter Name="original_username" Type="String" />
                <asp:Parameter Name="original_productname" Type="String" />
                <asp:Parameter Name="original_productpic" Type="String" />
                <asp:Parameter Name="original_price" Type="Int64" />
                <asp:Parameter Name="original_quantity" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
</p>
<p>
    <br />
</p>
<p>
</p>
<p>
</p>
<p>
</p>
<p>
</p>
</asp:Content>

